### ISSUE TITLE
Keyword not highlighting for python keywords

### ISSUE THREAD

**Issue by RealWei** [ifcanduela/batman-syntax#1]
Keywords such as "in", "is", "not", "and", "or" are not highlighted like "if" and "for"

![2015-10-08 23 17 16](https://cloud.githubusercontent.com/assets/6472829/10370735/ccceb75e-6e12-11e5-9112-968040af1c5e.png)

**Comment by ifcanduela** [comment]
Hi!

I published v1.0.1 with a specific rule to highlight python operators that should fix your issue.

Let me know if fit your needs, as I don't use Python.

**Comment by RealWei** [comment]
It works great!

Thank you for adding this in a short time.

**Comment by ifcanduela** [comment]
My pleasure :)
